// Centralized icon imports for better tree-shaking and maintainability
// Import each icon individually to reduce bundle size

export { default as Smile } from 'lucide-react/dist/esm/icons/smile'
export { default as Heart } from 'lucide-react/dist/esm/icons/heart'
export { default as Frown } from 'lucide-react/dist/esm/icons/frown'
export { default as Target } from 'lucide-react/dist/esm/icons/target'
export { default as Sparkles } from 'lucide-react/dist/esm/icons/sparkles'
export { default as Wind } from 'lucide-react/dist/esm/icons/wind'
export { default as Zap } from 'lucide-react/dist/esm/icons/zap'
export { default as Flower2 } from 'lucide-react/dist/esm/icons/flower-2'
export { default as X } from 'lucide-react/dist/esm/icons/x'
export { default as Check } from 'lucide-react/dist/esm/icons/check'
export { default as ArrowRight } from 'lucide-react/dist/esm/icons/arrow-right'
export { default as MoreVertical } from 'lucide-react/dist/esm/icons/more-vertical'
export { default as Edit2 } from 'lucide-react/dist/esm/icons/edit-2'
export { default as Sun } from 'lucide-react/dist/esm/icons/sun'
export { default as Moon } from 'lucide-react/dist/esm/icons/moon'
export { default as Star } from 'lucide-react/dist/esm/icons/star'
export { default as Coffee } from 'lucide-react/dist/esm/icons/coffee'
export { default as Music } from 'lucide-react/dist/esm/icons/music'
export { default as Book } from 'lucide-react/dist/esm/icons/book'
export { default as Dumbbell } from 'lucide-react/dist/esm/icons/dumbbell'
export { default as Palette } from 'lucide-react/dist/esm/icons/palette'
export { default as Eraser } from 'lucide-react/dist/esm/icons/eraser'
export { default as Trash2 } from 'lucide-react/dist/esm/icons/trash-2'
export { default as Home } from 'lucide-react/dist/esm/icons/home'
export { default as LogOut } from 'lucide-react/dist/esm/icons/log-out'
export { default as Crown } from 'lucide-react/dist/esm/icons/crown'
